# Generated by Django 3.2.8 on 2022-06-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
